### YamlMime:UniversalReference
items:
  - uid: azure-servicefabric.TestErrorChaosEvent
    name: TestErrorChaosEvent
    fullName: TestErrorChaosEvent
    children:
      - azure-servicefabric.TestErrorChaosEvent.kind
      - azure-servicefabric.TestErrorChaosEvent.reason
      - azure-servicefabric.TestErrorChaosEvent.timeStampUtc
    langs:
      - typeScript
    type: interface
    summary: |-
      <span data-ttu-id="3dd9b-101">Décrit un événement de Chaos est généré lorsqu’un événement inattendu se produit dans le moteur de Chaos.</span><span class="sxs-lookup"><span data-stu-id="3dd9b-101">Describes a Chaos event that gets generated when an unexpected event occurs in the Chaos engine.</span></span>
      <span data-ttu-id="3dd9b-102">Par exemple, en raison de l’instantané de cluster étant incohérent, lors de la défaillance d’une entité, le Chaos trouvé que l’entité a déjà généré une erreur--qui serait un événement inattendu.</span><span class="sxs-lookup"><span data-stu-id="3dd9b-102">For example, due to the cluster snapshot being inconsistent, while faulting an entity, Chaos found that the entity was already faulted -- which would be an unexpected event.</span></span>
    extends:
      name: azure-servicefabric.ChaosEvent
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.kind
    name: kind
    fullName: kind
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="3dd9b-103">Discriminateur polymorphe</span><span class="sxs-lookup"><span data-stu-id="3dd9b-103">Polymorphic Discriminator</span></span>
    syntax:
      content: 'kind: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.reason
    name: reason
    fullName: reason
    children: []
    langs:
      - typeScript
    type: property
    summary: '<span data-ttu-id="3dd9b-104">Décrit pourquoi TestErrorChaosEvent a été généré.</span><span class="sxs-lookup"><span data-stu-id="3dd9b-104">Describes why TestErrorChaosEvent was generated.</span></span> <span data-ttu-id="3dd9b-105">Par exemple, le Chaos tente une partition de l’erreur mais détecte que la partition n’est plus une tolérance de panne, puis un TestErrorEvent est généré avec la raison indiquant que la partition n’est pas une tolérance de panne.</span><span class="sxs-lookup"><span data-stu-id="3dd9b-105">For example, Chaos tries to fault a partition but finds that the partition is no longer fault tolerant, then a TestErrorEvent gets generated with the reason stating that the partition is not fault tolerant.</span></span>'
    optional: true
    syntax:
      content: 'reason?: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.timeStampUtc
    name: timeStampUtc
    fullName: timeStampUtc
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="3dd9b-106">L’horodatage UTC lorsque cet événement Chaos a été généré.</span><span class="sxs-lookup"><span data-stu-id="3dd9b-106">The UTC timestamp when this Chaos event was generated.</span></span>
    syntax:
      content: 'timeStampUtc: Date'
      return:
        type:
          - Date
    package: azure-servicefabric
references:
  - uid: azure-servicefabric.ChaosEvent
    name: ChaosEvent
    spec.typeScript:
      - name: ChaosEvent
        fullName: ChaosEvent
        uid: azure-servicefabric.ChaosEvent